<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
  xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
  xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd">
  <modelVersion>4.0.0</modelVersion>

  <parent>
    <groupId>org.springframework.boot</groupId>
    <artifactId>spring-boot-starter-parent</artifactId>
    <version>${bootVersion}</version>
    <relativePath />
  </parent>

  <groupId>${groupId}</groupId>
  <artifactId>${artifactId}</artifactId>
  <version>0.0.1-SNAPSHOT</version>
  <name>${projectName}</name>
  <description>${description}</description>

  <properties>
    <java.version>${javaVersion}</java.version>
    <jacoco.version>0.8.14</jacoco.version>
    <lombok.version>1.18.38</lombok.version>
    <spotless.version>2.43.0</spotless.version>
    <google-java-format.version>1.22.0</google-java-format.version>
    <archunit.version>1.3.0</archunit.version>
    <error-prone.version>2.42.0</error-prone.version>
    <maven-pmd-plugin.version>3.11.0</maven-pmd-plugin.version>
    <p3c-pmd.version>2.1.1</p3c-pmd.version>
    <p3c.failOnViolation>${p3cFailOnViolation?c}</p3c.failOnViolation>
    <p3c.skip>${p3cSkip?c}</p3c.skip>
  </properties>

  <dependencies>
    <dependency>
      <groupId>org.springframework.boot</groupId>
      <artifactId>spring-boot-starter-web</artifactId>
    </dependency>
    <dependency>
      <groupId>org.springframework.boot</groupId>
      <artifactId>spring-boot-starter-data-jpa</artifactId>
    </dependency>
    <dependency>
      <groupId>org.springframework.boot</groupId>
      <artifactId>spring-boot-starter-validation</artifactId>
    </dependency>
    <dependency>
      <groupId>org.springframework.boot</groupId>
      <artifactId>spring-boot-starter-aop</artifactId>
    </dependency>
    <dependency>
      <groupId>org.flywaydb</groupId>
      <artifactId>flyway-core</artifactId>
    </dependency>
    <dependency>
      <groupId>org.springframework.boot</groupId>
      <artifactId>spring-boot-starter-actuator</artifactId>
    </dependency>
<#if includeRedis>
    <dependency>
      <groupId>org.springframework.boot</groupId>
      <artifactId>spring-boot-starter-data-redis</artifactId>
    </dependency>
</#if>
<#if includePulsar>
    <dependency>
      <groupId>org.springframework.boot</groupId>
      <artifactId>spring-boot-starter-pulsar</artifactId>
    </dependency>
</#if>
    <dependency>
      <groupId>org.postgresql</groupId>
      <artifactId>postgresql</artifactId>
      <scope>runtime</scope>
    </dependency>
    <dependency>
      <groupId>org.projectlombok</groupId>
      <artifactId>lombok</artifactId>
      <version><#noparse>${lombok.version}</#noparse></version>
      <optional>true</optional>
    </dependency>
    <dependency>
      <groupId>org.springframework.boot</groupId>
      <artifactId>spring-boot-starter-test</artifactId>
      <scope>test</scope>
    </dependency>
    <dependency>
      <groupId>com.tngtech.archunit</groupId>
      <artifactId>archunit-junit5</artifactId>
      <version><#noparse>${archunit.version}</#noparse></version>
      <scope>test</scope>
    </dependency>
  </dependencies>

  <build>
    <plugins>
      <plugin>
        <groupId>org.springframework.boot</groupId>
        <artifactId>spring-boot-maven-plugin</artifactId>
      </plugin>
      <plugin>
        <groupId>org.apache.maven.plugins</groupId>
        <artifactId>maven-compiler-plugin</artifactId>
        <configuration>
          <showWarnings>true</showWarnings>
          <compilerArgs>
            <arg>-XDcompilePolicy=simple</arg>
            <arg>--should-stop=ifError=FLOW</arg>
            <arg>-Xplugin:ErrorProne</arg>
          </compilerArgs>
          <annotationProcessorPaths>
            <path>
              <groupId>org.projectlombok</groupId>
              <artifactId>lombok</artifactId>
              <version><#noparse>${lombok.version}</#noparse></version>
            </path>
            <path>
              <groupId>com.google.errorprone</groupId>
              <artifactId>error_prone_core</artifactId>
              <version><#noparse>${error-prone.version}</#noparse></version>
            </path>
          </annotationProcessorPaths>
        </configuration>
      </plugin>
      <plugin>
        <groupId>com.diffplug.spotless</groupId>
        <artifactId>spotless-maven-plugin</artifactId>
        <version><#noparse>${spotless.version}</#noparse></version>
        <configuration>
          <java>
            <googleJavaFormat>
              <version><#noparse>${google-java-format.version}</#noparse></version>
            </googleJavaFormat>
            <removeUnusedImports />
            <trimTrailingWhitespace />
            <endWithNewline />
          </java>
        </configuration>
        <executions>
          <execution>
            <id>spotless-apply</id>
            <phase>validate</phase>
            <goals>
              <goal>apply</goal>
            </goals>
          </execution>
          <execution>
            <id>spotless-check</id>
            <phase>verify</phase>
            <goals>
              <goal>check</goal>
            </goals>
          </execution>
        </executions>
      </plugin>
      <plugin>
        <groupId>org.jacoco</groupId>
        <artifactId>jacoco-maven-plugin</artifactId>
        <version><#noparse>${jacoco.version}</#noparse></version>
        <configuration>
          <excludes>
            <exclude>**/*Application*</exclude>
            <exclude>**/config/*</exclude>
            <exclude>**/repository/*</exclude>
            <exclude>**/entity/*</exclude>
            <exclude>**/dto/*</exclude>
            <exclude>**/dto/request/*</exclude>
            <exclude>**/dto/response/*</exclude>
            <exclude>**/vo/*</exclude>
            <exclude>**/annotation/*</exclude>
            <exclude>**/common/constant/*</exclude>
            <exclude>**/util/*</exclude>
            <exclude>**/service/DemoUserService*</exclude>
            <exclude>**/service/DemoRedisValueService*</exclude>
            <exclude>**/integration/pulsar/DemoPulsarProduceService*</exclude>
          </excludes>
        </configuration>
        <executions>
          <execution>
            <id>jacoco-agent</id>
            <goals>
              <goal>prepare-agent</goal>
            </goals>
          </execution>
          <execution>
            <id>jacoco-report</id>
            <phase>verify</phase>
            <goals>
              <goal>report</goal>
            </goals>
          </execution>
          <execution>
            <id>jacoco-check</id>
            <phase>verify</phase>
            <goals>
              <goal>check</goal>
            </goals>
            <configuration>
              <rules>
                <rule>
                  <element>BUNDLE</element>
                  <limits>
                    <limit>
                      <counter>INSTRUCTION</counter>
                      <value>COVEREDRATIO</value>
                      <minimum>1.00</minimum>
                    </limit>
                    <limit>
                      <counter>LINE</counter>
                      <value>COVEREDRATIO</value>
                      <minimum>1.00</minimum>
                    </limit>
                    <limit>
                      <counter>METHOD</counter>
                      <value>COVEREDRATIO</value>
                      <minimum>1.00</minimum>
                    </limit>
                  </limits>
                </rule>
              </rules>
            </configuration>
          </execution>
        </executions>
      </plugin>
      <plugin>
        <groupId>org.apache.maven.plugins</groupId>
        <artifactId>maven-pmd-plugin</artifactId>
        <version><#noparse>${maven-pmd-plugin.version}</#noparse></version>
        <configuration>
          <printFailingErrors>true</printFailingErrors>
          <targetJdk>1.8</targetJdk>
          <rulesets>
            <ruleset>rulesets/java/ali-comment.xml</ruleset>
            <ruleset>rulesets/java/ali-concurrent.xml</ruleset>
            <ruleset>rulesets/java/ali-constant.xml</ruleset>
            <ruleset>rulesets/java/ali-exception.xml</ruleset>
            <ruleset>rulesets/java/ali-flowcontrol.xml</ruleset>
            <ruleset>rulesets/java/ali-naming.xml</ruleset>
            <ruleset>rulesets/java/ali-oop.xml</ruleset>
            <ruleset>rulesets/java/ali-orm.xml</ruleset>
            <ruleset>rulesets/java/ali-other.xml</ruleset>
            <ruleset>rulesets/java/ali-set.xml</ruleset>
          </rulesets>
          <excludes>
            <exclude>**/generated/**</exclude>
          </excludes>
          <excludeRoots>
            <excludeRoot><#noparse>${project.basedir}</#noparse>/target/generated-sources</excludeRoot>
            <excludeRoot><#noparse>${project.basedir}</#noparse>/target/generated-test-sources</excludeRoot>
          </excludeRoots>
          <skip><#noparse>${p3c.skip}</#noparse></skip>
          <failOnViolation><#noparse>${p3c.failOnViolation}</#noparse></failOnViolation>
        </configuration>
        <executions>
          <execution>
            <id>p3c-check</id>
            <phase>verify</phase>
            <goals>
              <goal>check</goal>
            </goals>
          </execution>
        </executions>
        <dependencies>
          <dependency>
            <groupId>com.alibaba.p3c</groupId>
            <artifactId>p3c-pmd</artifactId>
            <version><#noparse>${p3c-pmd.version}</#noparse></version>
          </dependency>
        </dependencies>
      </plugin>
    </plugins>
  </build>

  <profiles>
    <profile>
      <id>p3c-advisory</id>
      <properties>
        <p3c.failOnViolation>false</p3c.failOnViolation>
        <p3c.skip>false</p3c.skip>
      </properties>
    </profile>
    <profile>
      <id>p3c-strict</id>
      <properties>
        <p3c.failOnViolation>true</p3c.failOnViolation>
        <p3c.skip>false</p3c.skip>
      </properties>
    </profile>
    <profile>
      <id>p3c-off</id>
      <properties>
        <p3c.skip>true</p3c.skip>
      </properties>
    </profile>
  </profiles>
</project>
