# ${projectName}

Generated by `java-proj-gen`.

## Coordinates

- groupId: `${groupId}`
- artifactId: `${artifactId}`
- package: `${packageName}`
- Spring Boot: `${bootVersion}`
- Java: `${javaVersion}`

## Architecture

项目已生成标准分层结构：

- `config`
- `controller`
- `service` / `service.impl`
- `repository`
- `entity`
- `proxy`（放置 `@FeignClient`）
- `dto.request` / `dto.response`
- `vo`
- `exception`
- `common.result` / `common.constant` / `common.enums`
- `util`
- `aspect`
- `annotation`

并内置一个可运行的 `DemoUser` CRUD Demo（可按真实业务直接替换）。

其中 `entity` 默认包含 `BaseEntity`，统一沉淀审计字段：

- `created_at`
- `created_by`
- `updated_at`
- `updated_by`

## Database

- Runtime: PostgreSQL + Flyway
- Test: 本地 PostgreSQL 专用测试库（默认 `postgres_test`）+ Flyway
- 测试数据清理：集成测试基类 `PostgresTestDataCleaner` 会在每个测试方法后自动清空业务表数据（保留 `flyway_schema_history`）

默认读取以下运行时环境变量：

- `SPRING_DATASOURCE_URL` (默认 `jdbc:postgresql://localhost:5432/postgres`)
- `SPRING_DATASOURCE_USERNAME` (默认 `postgres`)
- `SPRING_DATASOURCE_PASSWORD` (默认 `postgres`)

默认读取以下测试环境变量（`application-test.yml`）：

- `TEST_DB_URL` (默认 `jdbc:postgresql://localhost:5432/postgres_test`)
- `TEST_DB_USERNAME` (默认 `postgres`)
- `TEST_DB_PASSWORD` (默认 `postgres`)

## Optional Modules

<#if hasModules>
已启用：
<#list modules as module>
- `${module}`
</#list>
<#else>
- none
</#if>

<#if includeRedis>
- Redis 开关：`APP_REDIS_ENABLED=true`
- Redis 健康检查开关（可选）：`APP_REDIS_HEALTH_ENABLED=true`
</#if>
<#if includePulsarProducer>
- Pulsar Producer 开关：`APP_PULSAR_PRODUCER_ENABLED=true`
</#if>
<#if includePulsarConsumer>
- Pulsar Consumer 开关：`APP_PULSAR_CONSUMER_ENABLED=true`
</#if>
<#if includePulsar>
- Pulsar 健康检查开关（可选）：`APP_PULSAR_HEALTH_ENABLED=true`
</#if>

## Quick start

1. 启动 PostgreSQL（本地 Docker 示例）

```bash
docker run -d --name local-postgres \
  -e POSTGRES_USER=postgres \
  -e POSTGRES_PASSWORD=postgres \
  -e POSTGRES_DB=postgres \
  -p 5432:5432 postgres:16-alpine

# 创建专用测试库（已存在可忽略报错）
docker exec -i local-postgres psql -U postgres -d postgres \
  -c "CREATE DATABASE postgres_test;" || true
```

<#if includeRedis>
2. 启动 Redis（可选）

```bash
docker run -d --name local-redis -p 6379:6379 redis:7-alpine
```

</#if>
<#if includePulsar>
3. 启动 Pulsar（可选）

```bash
docker run -d --name local-pulsar -p 6650:6650 -p 8080:8080 \
  apachepulsar/pulsar:3.1.2 bin/pulsar standalone
```

</#if>
4. 执行质量门禁

```bash
mvn verify
```

5. 启动服务

```bash
mvn spring-boot:run
```

## Code Quality

项目已集成以下质量门禁：

- Spotless（google-java-format）强制统一格式
- Error Prone（`2.42.0`，JDK17 兼容版本）编译期静态检查
- p3c（基于 PMD）规约检查（默认开启）
- ArchUnit 分层与命名规则校验（包结构、后缀约束）
- JaCoCo 三个维度（Instruction / Line / Method）覆盖率 100%

p3c 默认模式（由脚手架参数 `--p3c-mode` 生成）：`${p3cMode}`

为保证 JDK17 下 Error Prone 正常运行，项目已生成 `.mvn/jvm.config`（包含 `--add-exports/--add-opens`）。

执行 `mvn verify` 会自动执行：

- `spotless:apply` + `spotless:check`
- Error Prone 编译期检查
- p3c 规约检查（默认 strict，命中违规阻断构建）
- ArchUnit 规则测试
- 单元测试 + E2E 测试
- JaCoCo 报告与覆盖率校验

建议使用 JDK 17 执行构建（与生成项目默认 Java 版本一致）。

## Maven Plugins

固定（默认启用）：

- `spring-boot-maven-plugin`
- `maven-compiler-plugin`（集成 Error Prone `2.42.0`）
- `spotless-maven-plugin`（`validate` 自动 `apply`，`verify` 自动 `check`）
- `jacoco-maven-plugin`（`verify` 执行 report/check，覆盖率门禁 100%）
- `maven-pmd-plugin` + `com.alibaba.p3c:p3c-pmd`（p3c 默认开启）
- `archunit-junit5`（测试阶段执行架构规则）

p3c 默认策略：

- `mvn verify` 默认执行 p3c 检查
- 默认 `failOnViolation=true`（strict）

模式差异：

| 模式 | 配置 | 构建结果 |
| --- | --- | --- |
| strict（默认） | `failOnViolation=true` | 命中违规即失败 |
| advisory | `failOnViolation=false` | 打印违规信息，但不因 p3c 失败 |
| off | `skip=true` | 跳过 p3c 检查 |

模式切换命令：

```bash
# 默认 strict
mvn verify

# advisory
mvn verify -Pp3c-advisory

# strict
mvn verify -Pp3c-strict

# off
mvn verify -Pp3c-off

# 属性覆盖
mvn verify -Dp3c.failOnViolation=true
mvn verify -Dp3c.failOnViolation=false
mvn verify -Dp3c.skip=true
```

内置 profile：

```xml
<profiles>
  <profile>
    <id>p3c-advisory</id>
    <properties>
      <p3c.failOnViolation>false</p3c.failOnViolation>
      <p3c.skip>false</p3c.skip>
    </properties>
  </profile>
  <profile>
    <id>p3c-strict</id>
    <properties>
      <p3c.failOnViolation>true</p3c.failOnViolation>
      <p3c.skip>false</p3c.skip>
    </properties>
  </profile>
  <profile>
    <id>p3c-off</id>
    <properties>
      <p3c.skip>true</p3c.skip>
    </properties>
  </profile>
</profiles>
```

## p3c 排除与白名单

目录/文件排除：

```xml
<excludes>
  <exclude>**/generated/**</exclude>
  <exclude>**/legacy/**</exclude>
</excludes>
<excludeRoots>
  <excludeRoot><#noparse>${project.basedir}</#noparse>/target/generated-sources</excludeRoot>
  <excludeRoot><#noparse>${project.basedir}</#noparse>/target/generated-test-sources</excludeRoot>
</excludeRoots>
```

如需白名单，可在 `maven-pmd-plugin` 中增加：

```xml
<excludeFromFailureFile><#noparse>${project.basedir}</#noparse>/config/pmd-exclude.properties</excludeFromFailureFile>
```

`config/pmd-exclude.properties` 示例：

```properties
com.acme.legacy.LegacyService=UnusedPrivateField,EmptyCatchBlock
```

按规则名排除（自定义 ruleset）：

```xml
<ruleset name="p3c-custom"
  xmlns="http://pmd.sourceforge.net/ruleset/2.0.0">
  <rule ref="rulesets/java/ali-naming.xml">
    <exclude name="BooleanPropertyShouldNotStartWithIsRule"/>
  </rule>
  <rule ref="rulesets/java/ali-oop.xml"/>
</ruleset>
```

代码内局部抑制（少量使用）：

```java
@SuppressWarnings("PMD.BooleanPropertyShouldNotStartWithIsRule")
// NOPMD
```

## 官方文档来源

- Spring Boot Maven Plugin: [官方文档](https://docs.spring.io/spring-boot/docs/current/maven-plugin/reference/htmlsingle/)
- Maven Compiler Plugin: [官方文档](https://maven.apache.org/plugins/maven-compiler-plugin/)
- Error Prone（安装与 Maven 配置）: [官方文档](https://errorprone.info/docs/installation)
- Spotless Maven Plugin: [官方文档](https://github.com/diffplug/spotless/tree/main/plugin-maven)
- google-java-format: [官方仓库](https://github.com/google/google-java-format)
- JaCoCo Maven Plugin: [官方文档](https://www.jacoco.org/jacoco/trunk/doc/maven.html)
- Maven PMD Plugin: [官方文档](https://maven.apache.org/plugins/maven-pmd-plugin/)
- PMD（规则集与抑制规则）: [规则集文档](https://docs.pmd-code.org/latest/pmd_userdocs_making_rulesets.html), [抑制文档](https://docs.pmd-code.org/latest/pmd_userdocs_suppressing_warnings.html)
- ArchUnit: [官方文档](https://www.archunit.org/)
- Alibaba p3c: [官方仓库](https://github.com/alibaba/p3c), [p3c-pmd 说明](https://github.com/alibaba/p3c/blob/master/p3c-pmd/README.md)
