package com.example.javaprojgen;

import java.nio.file.Path;
import java.util.ArrayList;
import java.util.LinkedHashSet;
import java.util.List;
import java.util.Locale;
import java.util.Map;
import java.util.Scanner;
import java.util.Set;
import java.util.concurrent.Callable;
import java.util.regex.Pattern;
import picocli.CommandLine;
import picocli.CommandLine.Command;
import picocli.CommandLine.Option;

@Command(
    name = "java-proj-gen",
    mixinStandardHelpOptions = true,
    description = "Generate a Spring Boot CRUD demo with layered architecture.")
/**
 * 生成器命令行入口。
 *
 * <p>这个类只负责三类事情：
 *
 * <p>1) 命令行参数定义与解析（Picocli）；
 *
 * <p>2) 交互式补全与参数校验；
 *
 * <p>3) 调用 {@link ProjectGenerator} 执行真正的项目文件生成。
 *
 * <p>设计目标是把“参数处理”与“模板渲染落盘”解耦，便于后续扩展更多开关、模块和输出格式。
 */
public class GeneratorMain implements Callable<Integer> {

  private static final Pattern COORD_RE = Pattern.compile("^[A-Za-z_][A-Za-z0-9_.-]*$");
  private static final Pattern PACKAGE_RE =
      Pattern.compile("^[a-z][a-z0-9_]*(\\.[a-z][a-z0-9_]*)*$");
  private static final Pattern PROJECT_RE = Pattern.compile("^[A-Za-z0-9][A-Za-z0-9-]*$");
  private static final Pattern SEMVER_RE = Pattern.compile("^\\d+\\.\\d+(\\.\\d+)?$");
  private static final Pattern BOOT_LINE_RE = Pattern.compile("^\\d+\\.\\d+$");
  private static final Set<String> P3C_MODES = Set.of("strict", "advisory", "off");
  private static final Map<String, ModuleDefinition> MODULE_REGISTRY = ModuleCatalog.modules();

  private final ProjectGenerator projectGenerator = new ProjectGenerator(MODULE_REGISTRY);

  @Option(names = "--project-name")
  private String projectName = "demo-service";

  @Option(names = "--group-id")
  private String groupId = "com.example";

  @Option(names = "--artifact-id")
  private String artifactId = "demo-service";

  @Option(names = "--package-name")
  private String packageName;

  @Option(names = "--description")
  private String description = "Generated by java-proj-gen";

  @Option(names = "--java-version")
  private String javaVersion = "17";

  @Option(names = "--boot-version")
  private String bootVersion = "3.2.12";

  @Option(
      names = "--boot-line",
      description = "Expected Spring Boot release line, e.g. 3.2. Use * to skip line check.")
  private String bootLine = "3.2";

  @Option(names = "--port")
  private int port = 8080;

  @Option(names = "--modules", description = "Comma-separated module ids, e.g. redis,pulsar-producer")
  private String modulesCsv = "";

  @Option(
      names = "--p3c-mode",
      description = "p3c mode: strict|advisory|off (default: ${DEFAULT-VALUE})")
  private String p3cMode = "strict";

  @Option(names = "--output")
  private Path output = Path.of(".");

  @Option(names = "--force")
  private boolean force;

  @Option(names = "--interactive")
  private boolean interactive;

  /** CLI 主函数，交给 Picocli 完成参数解析与执行。 */
  public static void main(String[] args) {
    int exitCode = new CommandLine(new GeneratorMain()).execute(args);
    System.exit(exitCode);
  }

  @Override
  /**
   * 命令执行入口。
   *
   * <p>返回码约定：
   *
   * <p>- `0`：执行成功，项目已生成；
   *
   * <p>- `2`：参数校验失败或生成过程中出现异常。
   */
  public Integer call() {
    try {
      ProjectConfig config = buildConfig();
      Path projectPath = projectGenerator.generate(config);
      System.out.println("[OK] Project generated");
      System.out.println("     path: " + projectPath);
      System.out.println("     package: " + config.packageName());
      List<String> modules = sortedModules(config.modules());
      System.out.println("     modules: " + (modules.isEmpty() ? "none" : String.join(", ", modules)));
      System.out.println("     p3c mode: " + config.p3cMode());
      System.out.println();
      System.out.println("Next steps:");
      System.out.println("  cd " + projectPath);
      System.out.println("  mvn verify");
      System.out.println("  mvn spring-boot:run");
      return 0;
    } catch (Exception ex) {
      System.err.println("[ERROR] " + ex.getMessage());
      return 2;
    }
  }

  /**
   * 构建最终配置对象。
   *
   * <p>处理顺序：
   *
   * <p>1) 先补默认 packageName；
   *
   * <p>2) 再基于命令行参数构造草稿；
   *
   * <p>3) 如果开启交互模式，则允许用户逐项覆盖；
   *
   * <p>4) 最后统一校验，确保下游生成器拿到的是“可执行配置”。
   */
  private ProjectConfig buildConfig() {
    String resolvedPackage = packageName;
    if (resolvedPackage == null || resolvedPackage.isBlank()) {
      resolvedPackage = buildDefaultPackage(groupId, artifactId);
    }

    ProjectConfig draft =
        new ProjectConfig(
            projectName,
            groupId,
            artifactId,
            resolvedPackage,
            description,
            javaVersion,
            bootVersion,
            bootLine,
            port,
            parseModules(modulesCsv),
            normalizeP3cMode(p3cMode),
            output.toAbsolutePath().normalize(),
            force);

    if (interactive) {
      draft = fillInteractive(draft);
    }

    validate(draft);
    return draft;
  }

  /**
   * 交互式补全配置。
   *
   * <p>当用户传入 `--interactive` 时触发；每个字段都支持“直接回车沿用默认值”。
   */
  private ProjectConfig fillInteractive(ProjectConfig draft) {
    Scanner scanner = new Scanner(System.in);

    String project = prompt(scanner, "projectName", draft.projectName());
    String group = prompt(scanner, "groupId", draft.groupId());
    String artifact = prompt(scanner, "artifactId", draft.artifactId());
    String pkg = prompt(scanner, "packageName", draft.packageName());
    String desc = prompt(scanner, "description", draft.description());
    String javaVer = prompt(scanner, "javaVersion", draft.javaVersion());
    String bootVer = prompt(scanner, "bootVersion", draft.bootVersion());
    String expectedBootLine = prompt(scanner, "bootLine (* or x.y)", draft.bootLine());
    String selectedP3cMode =
        normalizeP3cMode(prompt(scanner, "p3cMode (strict|advisory|off)", draft.p3cMode()));
    int serverPort = promptPort(scanner, draft.port());
    Path targetOutput =
        Path.of(prompt(scanner, "output directory", draft.output().toString()))
            .toAbsolutePath()
            .normalize();

    Set<String> modules = new LinkedHashSet<>();
    for (ModuleDefinition module : MODULE_REGISTRY.values()) {
      boolean enabled = promptYesNo(scanner, module.promptLabel(), draft.modules().contains(module.id()));
      if (enabled) {
        modules.add(module.id());
      }
    }

    return new ProjectConfig(
        project,
        group,
        artifact,
        pkg,
        desc,
        javaVer,
        bootVer,
        expectedBootLine,
        serverPort,
        modules,
        selectedP3cMode,
        targetOutput,
        draft.force());
  }

  /** 通用字符串提示函数：展示默认值，空输入则返回默认值。 */
  private String prompt(Scanner scanner, String label, String defaultValue) {
    System.out.print(label + " [" + defaultValue + "]: ");
    String line = scanner.nextLine().trim();
    return line.isEmpty() ? defaultValue : line;
  }

  /** 端口提示函数：循环校验直到输入合法（1~65535）。 */
  private int promptPort(Scanner scanner, int defaultPort) {
    while (true) {
      String rawPort = prompt(scanner, "serverPort", String.valueOf(defaultPort));
      try {
        int parsedPort = Integer.parseInt(rawPort);
        if (parsedPort < 1 || parsedPort > 65535) {
          System.out.println("serverPort must be between 1 and 65535.");
          continue;
        }
        return parsedPort;
      } catch (NumberFormatException ex) {
        System.out.println("serverPort must be a number.");
      }
    }
  }

  /** 是/否提示函数：支持 `y/yes`，空输入按默认值处理。 */
  private boolean promptYesNo(Scanner scanner, String label, boolean defaultYes) {
    String hint = defaultYes ? "Y/n" : "y/N";
    System.out.print(label + " (" + hint + "): ");
    String line = scanner.nextLine().trim().toLowerCase(Locale.ROOT);
    if (line.isEmpty()) {
      return defaultYes;
    }
    return line.equals("y") || line.equals("yes");
  }

  /**
   * 解析可选模块列表。
   *
   * <p>输入格式：`redis,pulsar-producer,pulsar-consumer`
   *
   * <p>解析策略：去空白、转小写、去重、并校验模块是否在注册表中。
   */
  private Set<String> parseModules(String value) {
    Set<String> result = new LinkedHashSet<>();
    if (value == null || value.isBlank()) {
      return result;
    }

    for (String token : value.split(",")) {
      String moduleId = token.trim().toLowerCase(Locale.ROOT);
      if (moduleId.isEmpty()) {
        continue;
      }
      if (!MODULE_REGISTRY.containsKey(moduleId)) {
        throw new IllegalArgumentException(
            "unsupported module: "
                + moduleId
                + "; allowed: "
                + String.join(", ", MODULE_REGISTRY.keySet()));
      }
      result.add(moduleId);
    }
    return result;
  }

  /** 对模块 ID 进行稳定排序，确保日志输出与模板变量顺序可预测。 */
  private List<String> sortedModules(Set<String> modules) {
    List<String> sorted = new ArrayList<>(modules);
    sorted.sort(String::compareTo);
    return List.copyOf(sorted);
  }

  /** 归一化 p3c 模式；空值回落到默认 strict。 */
  private String normalizeP3cMode(String value) {
    if (value == null || value.isBlank()) {
      return "strict";
    }
    return value.trim().toLowerCase(Locale.ROOT);
  }

  /**
   * 参数合法性校验。
   *
   * <p>这里做“快速失败”，避免进入模板渲染后才发现错误。
   */
  private void validate(ProjectConfig config) {
    if (!PROJECT_RE.matcher(config.projectName()).matches()) {
      throw new IllegalArgumentException("invalid projectName: " + config.projectName());
    }
    if (!COORD_RE.matcher(config.groupId()).matches()) {
      throw new IllegalArgumentException("invalid groupId: " + config.groupId());
    }
    if (!COORD_RE.matcher(config.artifactId()).matches()) {
      throw new IllegalArgumentException("invalid artifactId: " + config.artifactId());
    }
    if (!PACKAGE_RE.matcher(config.packageName()).matches()) {
      throw new IllegalArgumentException("invalid packageName: " + config.packageName());
    }
    if (!config.javaVersion().matches("^\\d+$")) {
      throw new IllegalArgumentException("invalid javaVersion: " + config.javaVersion());
    }
    if (!SEMVER_RE.matcher(config.bootVersion()).matches()) {
      throw new IllegalArgumentException(
          "invalid bootVersion: "
              + config.bootVersion()
              + " (expected semantic version, e.g. 3.2.12)");
    }
    if (!("*".equals(config.bootLine()) || BOOT_LINE_RE.matcher(config.bootLine()).matches())) {
      throw new IllegalArgumentException(
          "invalid bootLine: " + config.bootLine() + " (expected '*' or x.y)");
    }
    if (!"*".equals(config.bootLine())
        && !config.bootVersion().equals(config.bootLine())
        && !config.bootVersion().startsWith(config.bootLine() + ".")) {
      throw new IllegalArgumentException(
          "bootVersion "
              + config.bootVersion()
              + " is not in expected line "
              + config.bootLine()
              + " (set --boot-line=* to disable this check)");
    }
    if (config.port() < 1 || config.port() > 65535) {
      throw new IllegalArgumentException("invalid port: " + config.port());
    }
    if (!P3C_MODES.contains(config.p3cMode())) {
      throw new IllegalArgumentException(
          "invalid p3cMode: "
              + config.p3cMode()
              + " (expected one of: "
              + String.join(", ", P3C_MODES)
              + ")");
    }
  }

  /**
   * 根据 `groupId + artifactId` 自动推导默认包名。
   *
   * <p>示例：`com.example` + `demo-service` -> `com.example.demoservice`
   */
  private String buildDefaultPackage(String group, String artifact) {
    String suffix = artifact.replaceAll("[^A-Za-z0-9]+", "").toLowerCase(Locale.ROOT);
    if (suffix.isBlank()) {
      suffix = "app";
    }
    return group.toLowerCase(Locale.ROOT) + "." + suffix;
  }
}
